//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo03.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Modificado { get; set; }
        public int IdAutor { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
